#!/bin/bash
ADDR=$1; shift

export AUTOSSH="/usr/local/src/autossh-1.4c/autossh"

export AUTOSSH_LOGFILE="/tmp/autossh.log"
export AUTOSSH_DEBUG=yes
export AUTOSSH_PORT=20000

${AUTOSSH} -t "${ADDR}" "$@"
